FROM python:3.11-slim

WORKDIR /app

# Install pip dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy all your code into /app
COPY . .

# Default: run Python, script chosen later
ENTRYPOINT ["python"]
CMD ["afp.py"]
